[package]
name = "ed25519t"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "1.0.1"
sha2 = "*"
rand = "*"
hex = "0.4"
bs58 = "0.4"
