[package]
name = "ch12"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
libc = "0.2"
setjmp = "0.1.4"
